name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:  
  build:
    name: Build
    runs-on: ubuntu-24.04
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write 

    steps:    

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
        

      - name: login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create devcontainer      
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/.devcontainer.json
          imageName: ghcr.io/${{ github.repository_owner }}/repico_devcontainer
          cacheFrom: ghcr.io/${{ github.repository_owner }}/repico_devcontainer
          push: always

      - name: Build 1551-III-Pico
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/.devcontainer.json
          imageName: ghcr.io/${{ github.repository_owner }}/repico_devcontainer
          runCmd: |
            cd /workspaces/1541-rePico
            mkdir -p build
            cd build
            cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -S /workspaces/1541-rePico/firmware-1551-III-pico -B /workspaces/1541-rePico/build -G Ninja
            cmake --build . --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1551-III-Pico-binaries 
          path: |
            build/1551-III-Pico.uf2
            build/1551-III-Pico.elf
