M48
; DRILL file {KiCad 9.0.7} date 2026-07-16T22:19:32+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-16T22:19:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X156.191Y-147.283
X156.191Y-152.133
T2
X159.221Y-146.983
X159.221Y-152.433
M30
